### ISSUE TITLE
No bin

### ISSUE THREAD

**Issue by aredridel** [hamin/kyatchi#1]
Just trying out kyatchi and seeing that npm won't install it for me since there's no `bin/kyatchi.js` as mentioned in the `package.json`.

Works great from a git clone though. Nice work!

**Comment by hamin** [comment]
mistakingly committed an experimental branch :)

**Comment by hamin** [comment]
so this issue is fixed but i'm unable to push a new version of the package to npm registry, running into a werid bug with npm, will let you know as soon as its up. Thanks for reporting the issue @aredridel

**Comment by hamin** [comment]
@aredridel new version of kyatchi has been published to npm. npm install kyatchi now works. btw, kyatchi was mentioned on the Javascript Weekly newsletter :)

**Comment by aredridel** [comment]
Sweet!
