### ISSUE TITLE
instalation problem

### ISSUE THREAD

**Issue by dgertych-monterail** [hamin/kyatchi#2]
Hi! I'm new in nodejs. During instalation I'm getting this problem any idea how to resolve?

npm install kyatchi

npm info it worked if it ends with ok
npm info using npm@0.3.18
npm info using node@v0.4.8
npm info range faye@>=0.6
npm info range smtp@>= 0.1.0
npm info range jade@>= 0.12.0
npm info range express@>= 2.3.10
npm info range mime@>= 0.0.1
npm info range qs@>= 0.0.6
npm info range connect@>= 1.4.1 < 2.0.0
npm info preinstall mime@1.2.2
npm info preinstall redis@0.6.0
npm info preinstall faye@0.6.1
npm info preinstall express@2.3.11
npm info preinstall connect@1.4.3
npm info preinstall kyatchi@0.0.1
npm info preinstall jade@0.12.1
npm info preinstall qs@0.1.0
npm info preinstall smtp@0.1.0
npm ERR! failed to link bins
npm ERR! install failed Error: ENOENT, No such file or directory '/usr/local/bin/kyatchi@0.0.1'
npm info install failed rollback
npm info uninstall [ 'kyatchi@0.0.1',
npm info uninstall   'faye@0.6.1',
npm info uninstall   'smtp@0.1.0',
npm info uninstall   'jade@0.12.1',
npm info uninstall   'express@2.3.11',
npm info uninstall   'redis@0.6.0',
npm info uninstall   'mime@1.2.2',
npm info uninstall   'qs@0.1.0',
npm info uninstall   'connect@1.4.3' ]
npm info preuninstall kyatchi@0.0.1
npm info preuninstall faye@0.6.1
npm info preuninstall smtp@0.1.0
npm info preuninstall jade@0.12.1
npm info preuninstall express@2.3.11
npm info preuninstall redis@0.6.0
npm info preuninstall mime@1.2.2
npm info preuninstall qs@0.1.0
npm info preuninstall connect@1.4.3
npm info uninstall kyatchi@0.0.1
npm info uninstall faye@0.6.1
npm info uninstall smtp@0.1.0
npm info uninstall jade@0.12.1
npm info uninstall express@2.3.11
npm info uninstall redis@0.6.0
npm info uninstall mime@1.2.2
npm info uninstall qs@0.1.0
npm info uninstall connect@1.4.3
npm info auto-deactive not symlink
npm info auto-deactive not symlink
npm info auto-deactive not symlink
npm info auto-deactive not symlink
npm info auto-deactive not symlink
npm info auto-deactive not symlink
npm info auto-deactive not symlink
npm info auto-deactive not symlink
npm info auto-deactive not symlink
npm info postuninstall kyatchi@0.0.1
npm info postuninstall faye@0.6.1
npm info postuninstall smtp@0.1.0
npm info postuninstall jade@0.12.1
npm info postuninstall express@2.3.11
npm info postuninstall redis@0.6.0
npm info postuninstall mime@1.2.2
npm info postuninstall qs@0.1.0
npm info postuninstall connect@1.4.3
npm info uninstall faye@0.6.1 complete
npm info uninstall mime@1.2.2 complete
npm info uninstall express@2.3.11 complete
npm info uninstall kyatchi@0.0.1 complete
npm info uninstall redis@0.6.0 complete
npm info uninstall connect@1.4.3 complete
npm info uninstall smtp@0.1.0 complete
npm info uninstall jade@0.12.1 complete
npm info uninstall qs@0.1.0 complete
npm info install failed rolled back
npm ERR! Error: ENOENT, No such file or directory '/usr/local/bin/kyatchi@0.0.1'
npm ERR! Report this _entire_ log at http://github.com/isaacs/npm/issues
npm ERR! or email it to npm-@googlegroups.com
npm ERR! Just tweeting a tiny part of the error will not be helpful.
npm ERR! System Darwin 10.7.0
npm ERR! argv { remain: 
npm ERR! argv    [ 'kyatchi',
npm ERR! argv      'coffee-script@>=1.1.1',
npm ERR! argv      'express@>= 2.3.10',
npm ERR! argv      'jade@>= 0.12.0',
npm ERR! argv      'faye@>=0.6',
npm ERR! argv      'smtp@>= 0.1.0',
npm ERR! argv      'redis',
npm ERR! argv      'connect@>= 1.4.1 < 2.0.0',
npm ERR! argv      'mime@>= 0.0.1',
npm ERR! argv      'qs@>= 0.0.6',
npm ERR! argv      'qs@>= 0.0.6',
npm ERR! argv      'mime@>= 0.0.1' ],
npm ERR! argv   cooked: [ 'install', 'kyatchi' ],
npm ERR! argv   original: [ 'install', 'kyatchi' ] }
npm not ok

**Comment by hamin** [comment]
@chytreg sorry about the issue, i've made the fix on the github master branch, i can't publish to the npm package at the moment since and I'm trying to resolve with the npm maintainers. In the meantime you can just clone the github repo and install kyatchi's dependencies (coffee-script, express, jade, faye, and smtp) from npm (via npm install <dependency-name>). Sorry about the inconvenience I should probably have the npm package issue resolved later today.

**Comment by dgertych-monterail** [comment]
ok, thanks for a quick response :)

**Comment by hamin** [comment]
the issue has been fixed, you should now be able to install :)

**Comment by dgertych-monterail** [comment]
Works great thanks dude!

**Comment by hamin** [comment]
awesome, @chytreg do you think you have a screenshot that I could use? just a screenshot of an email in Kyatchi. Thanks if you can
