### ISSUE TITLE
should be able to turn off desktop notifications

### ISSUE THREAD

**Issue by hamin** [hamin/kyatchi#9]
when a user starts kyatchi, they should be able to turn off the desktop notifications (grown and libnotify). The notifications should be turned on by default.

**Comment by Finkregh** [comment]
any news on this? would something like a bounty speed things up? :D

**Comment by CoderBounty** [comment]
A bounty has been placed on this issue, check it out at Coder Bounty! http://coderbounty.com/#24

**Comment by hamin** [comment]
lol @Finkregh i'll get on it this weekend, they're a buch of things i wanted to do including upgrading the project to node 0.6.x when I'm done, that $40 is mine :)

**Comment by Finkregh** [comment]
@hamin i'd set another bounty if you'd have a working patch :o

**Comment by hamin** [comment]
@Finkregh I actually do have something working, I just wanted to wait and deal with some of the other issues first, but if there is a demand for this (much to my surprise and pleasure :) ) I'll push something tonight. @Finkregh another bounty would be much appreciated :)

**Comment by hamin** [comment]
@Finkregh so this should be fixed, issues #6 and #7 are fixed on master. Just check out master for now and if it works I will publish an update on the package on npm.

**Comment by Finkregh** [comment]
please reopen this and i'll place another bounty.

```
# npm start -s

> kyatchi@0.0.4 start /root/dev/node-apps/kyatchi
> coffee app.coffee

The "sys" module is now called "util". It should have a similar interface.
Kyatchi - Catch the Mail!

Options:
  --web, -w     Web interface for viewing the incoming emails                     [default: 1080]
  --mail, -m    SMTP Mail Server for incoming emails                              [default: 1025]
  --silent, -s  Turns off OS notifications for incoming emails (Growl/LibNotify)  [boolean]

SMTP server running on port 1025
Kyatchi web interface started on port 1080 - http://0.0.0.0:1080

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: undefined is not a function
    at /root/dev/node-apps/kyatchi/node_modules/libnotify/lib/libnotify.js:61:21
    at /root/dev/node-apps/kyatchi/node_modules/libnotify/lib/libnotify.js:26:14
    at ChildProcess.exithandler (child_process.js:287:7)
    at ChildProcess.emit (events.js:70:17)
    at maybeExit (child_process.js:361:16)
    at Socket.<anonymous> (child_process.js:466:7)
    at Socket.emit (events.js:67:17)
    at Array.0 (net.js:320:10)
    at EventEmitter._tickCallback (node.js:192:40)
```

at the other end:

```
> swaks -s foo@bar -t bar@foo -s host
=== Trying host:25...
=== Connected to host.
<-  220 hostname.unconfigured ESMTP node.js
 -> EHLO x
<-  250-hostname.unconfigured
<-  250 HELP
 -> MAIL FROM:<root@x>
<-  250 MAIL FROM looks good enough for me.
 -> RCPT TO:<bar@foo>
<-  250 RCPT TO ...I hope that's right. I didn't check.)
 -> DATA
<-  354 Enter mail, end with "." on a line by itself
 -> Date: Tue, 15 May 2012 09:43:28 +0200
 -> To: bar@foo
 -> From: root@x
 -> Subject: test Tue, 15 May 2012 09:43:28 +0200
 -> X-Mailer: swaks v20100211.0 jetmore.org/john/code/swaks/
 -> 
 -> This is a test mailing
 -> 
 -> .
<-  250 Message Accepted
 -> QUIT
*** Remote host closed connection unexpectedly.
```

**Comment by hamin** [comment]
@Finkregh what version of node are you running? Master currently is only 0.4.x compliant. 0.6.x compatibility will take a bit longer, i'll have it done this week.

**Comment by Finkregh** [comment]
yeah, that might have been the problem ;D

(please reopen)

**Comment by CoderBounty** [comment]
hamin, you have won a bounty at Coder Bounty!  Login and verify your Github username within 30 days to claim it.  http://coderbounty.com
